/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lvxingpai.yunkai;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ChatGroupProp implements org.apache.thrift.TEnum {
  CHAT_GROUP_ID(0),
  NAME(1),
  GROUP_DESC(2),
  GROUP_TYPE(3),
  AVATAR(4),
  TAGS(5),
  CREATOR(6),
  ADMIN(7),
  PARTICIPANTS(8),
  MAX_USERS(9),
  CREATE_TIME(10),
  UPDATE_TIME(11),
  VISIBLE(12);

  private final int value;

  private ChatGroupProp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChatGroupProp findByValue(int value) { 
    switch (value) {
      case 0:
        return CHAT_GROUP_ID;
      case 1:
        return NAME;
      case 2:
        return GROUP_DESC;
      case 3:
        return GROUP_TYPE;
      case 4:
        return AVATAR;
      case 5:
        return TAGS;
      case 6:
        return CREATOR;
      case 7:
        return ADMIN;
      case 8:
        return PARTICIPANTS;
      case 9:
        return MAX_USERS;
      case 10:
        return CREATE_TIME;
      case 11:
        return UPDATE_TIME;
      case 12:
        return VISIBLE;
      default:
        return null;
    }
  }
}
