/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lvxingpai.yunkai;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserInfoProp implements org.apache.thrift.TEnum {
  USER_ID(0),
  NICK_NAME(1),
  AVATAR(2),
  GENDER(3),
  SIGNATURE(4),
  TEL(5);

  private final int value;

  private UserInfoProp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserInfoProp findByValue(int value) { 
    switch (value) {
      case 0:
        return USER_ID;
      case 1:
        return NICK_NAME;
      case 2:
        return AVATAR;
      case 3:
        return GENDER;
      case 4:
        return SIGNATURE;
      case 5:
        return TEL;
      default:
        return null;
    }
  }
}
